DROP TABLE IF EXISTS REQUEST, INPUTDATA, OUTPUTDATA;

CREATE TABLE REQUEST (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    requestIp VARCHAR(15) NOT NULL,
    executeTime TIME NOT NULL,
    sourceCode VARCHAR(2) NULL_TO_DEFAULT,
    targetCode VARCHAR(2) NOT NULL
);

CREATE TABLE INPUTDATA (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    requestID LONG NOT NULL,
    FOREIGN KEY(requestID) REFERENCES request(id)
);

CREATE TABLE OUTPUTDATA (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    requestID LONG NOT NULL,
    FOREIGN KEY(requestID) REFERENCES request(id)
);