DROP TABLE IF EXISTS REQUEST, INPUTDATA, OUTPUTDATA;

CREATE TABLE REQUEST (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    requestIp VARCHAR(15) NOT NULL,
    executeTime TIME NOT NULL,
    translateParam VARCHAR(6) NOT NULL
);

CREATE TABLE INPUTDATA (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    requestID LONG NOT NULL,
    FOREIGN KEY(requestID) REFERENCES request(id)
);

CREATE TABLE OUTPUTDATA (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    requestID LONG NOT NULL,
    FOREIGN KEY(requestID) REFERENCES request(id)
);